version: '3.8'

services:
  web:
    build: ./web
    container_name: web-server
    command: npm run dev
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./nft_volume:/data/db
    ports:
      - "27017:27017"

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444

  scrapers:
    build: ./scrapers
    container_name: scrapers
    ports:
     - "8888:8888"
    command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    #command: ["pipenv", "run", "python", "nft.py"]
    depends_on: 
      - selenium
      - api
    volumes:
      - ./scrapers:/home/dev/code/

networks:
  default:
    driver: bridge

volumes:
  nft_volume:
